### ISSUE TITLE
VPAID Ad Events not firing

### ISSUE THREAD

**Issue by yadavharsh** [Manbearpixel/videojs-vpaid#2]
Hi,

I am trying to use the plugin. Its working good so far, though I cannot get the VPAID ad events to fire:
adstart, adend, adtimeout, etc.

I need the events to start/stop the content video and fire other events.

Thanks

**Comment by joshmadewell** [comment]
@yadavharsh  I'd make a PR with this for you but I don't have the need for those changes.

Also...the "vpaid_AdStarted" and "vpaid_AdComplete" event should both be firing. If you want to go through and ad the stuff yourself, the code for the listeners is writting in src/com/videojs/vpaid/AdContainer.as file

**Comment by Manbearpixel** [comment]
@yadavharsh 
Please download the most current version of this repo to view all the events you can currently tie with your VideoJS setup. I have included support for what you needed and more.
